### ISSUE TITLE
hi    !!! Exception during processing !!! module 'whisper' has no attribute 'load_model'

### ISSUE THREAD

**Issue by 1zhangyy1** [yuvraj108c/ComfyUI-Whisper#9]
!!! Exception during processing !!! module 'whisper' has no attribute 'load_model'
Traceback (most recent call last):
File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Whisper/apply_whisper.py", line 33, in apply_whisper
model = whisper.load_model(model)
AttributeError: module 'whisper' has no attribute 'load_model'

**Comment by ansorre** [comment]
Same here!

**Comment by Bastrijdesign** [comment]
did you find any fix for this?
